CREATE SCHEMA IF NOT EXISTS BLOG AUTHORIZATION sa;

DROP TABLE IF EXISTS BLOG.TBL_BLOGS;

CREATE TABLE BLOG.TBL_BLOGS (
  blog_id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  blog TEXT DEFAULT NULL
);

CREATE TABLE BLOG.TBL_COMMENTS (
  comment_id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  comment_text TEXT DEFAULT NULL,
  blog_id INT NOT NULL
);

ALTER TABLE BLOG.TBL_COMMENTS
ADD FOREIGN KEY (blog_id) REFERENCES BLOG.TBL_BLOGS(blog_id);